### PR TITLE
Fixes in the demo

### PR DESCRIPTION
**Pull request by rmeister**
Demo is functional now. Remaining issue is the transmission quality of WebJack. The likelihood is high that it needs a couple of page reloads until the board is detected correctly. 

Already updated the required WebJack version, although 0.1.2 is not existing yet. So probably we should merge the fix-decoder branch of WebJack first and create a new release before merging this PR.

### CODE REVIEW

**Comment by jywarren** [comment]
OK, though you can probably say `~0.1.1` for version and it'll just get the next one as it's published. This looks really cool, and maybe needs a quick youtube demo or something to introduce it!

Could we change the intro text to "Firmata is a RPC like protocol, that defines a serial interface to read from or write to a microcontroller's pins"

**Comment by jywarren** [comment]
Also could we briefly clarify what you have to have installed/modified on the Arduino to get it to work?

**Comment by jywarren** [comment]
And, just speculating here, but we could for example relate to this page, where it shows what pins we can access: http://johnny-five.io/platform-support/

**Comment by rmeister** [comment]
> OK, though you can probably say ~0.1.1 for version and it'll just get the next one as it's published.

Cool, thanks for the hint! Will be included with other changes related to your feedback.

> And, just speculating here, but we could for example relate to this page, where it shows what pins we can access:

Do you mean only the Arduino pins? http://johnny-five.io/platform-support/#arduino-uno
Cause I doubt we will get to run SoftModem on all of these boards.

**Comment by rmeister** [comment]
Can we merge this, so the demo is functional?

**Comment by jywarren** [comment]
Go for it ! Do I need to add you as a collaborator?

**Comment by jywarren** [comment]
nope, you already are. +1

**Comment by rmeister** [comment]
Ok cool :smile:  just didn't wanted to pass you over.

**Comment by jywarren** [comment]
Yep, I appreciate the notice when you do merge!

**Pull request merged**
